
name: build-images
on:
  push:
    branches:
    - main
  # pull_request:
  # schedule:
  # - cron: '25 4 * * 4'
  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: .
      tag: latest
    secrets: inherit

  build-with-node:
    needs:
    - build-base
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: with-node
      tag: with-node
      parent: latest
    secrets: inherit

  build-with-puppeteer:
    needs:
    - build-with-node
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: with-puppeteer
      tag: with-puppeteer
      parent: with-node
    secrets: inherit

  build-with-puppeteer-xvfb:
    needs:
    - build-with-puppeteer
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: with-puppeteer-xvfb
      tag: with-puppeteer-xvfb
      parent: with-puppeteer
    secrets: inherit

  build-with-puppeteer-xvfb-ffmpeg:
    needs:
    - build-with-puppeteer
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: with-puppeteer-xvfb-ffmpeg
      tag: with-puppeteer-xvfb-ffmpeg
      parent: with-puppeteer
    secrets: inherit