
name: build-images
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '25 4 * * 4'
  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/build-image.yaml
    with:
      folder: .
      tag: latest
    secrets: inherit
